# File: alert/src/main/resources/application.yml
spring:
  application:
    name: ${APP_NAME:alert-service}
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false  #JSON 데이터에 Java 객체에 매핑되지 않는 필드가 있어도 에러를 발생시키지 않음
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:mongodb}:${MONGODB_PASSWORD:mongodb}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DB:telecomdb}?authSource=admin

server:
  port: ${SERVER_PORT:80}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    com.telecom.alert: ${LOG_LEVEL:DEBUG}
    org.springframework.web: INFO

event-grid:
  endpoint: ${EVENT_GRID_ENDPOINT}
  key: ${EVENT_GRID_KEY}
  topic: ${EVENT_GRID_TOPIC}